
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 20 19:54:14 CEST 2016
//----------------------------------------------------

package pl.edu.wat.wcy.jfa.parser;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int MINUS = 4;
  public static final int MULTI = 5;
  public static final int MOD = 7;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int LPAREN = 8;
  public static final int INTEGER_LITERAL = 2;
}

